### ISSUE TITLE
TrueValue config does not seem to work

### ISSUE THREAD

**Issue by lookyman** [infection/infection#1226]
```json
{
    "timeout": 10,
    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "text": "infection-log.txt"
    },
    "mutators": {
        "TrueValue": {
            "settings": {
                "in_array": false,
                "array_search": false
            }
        }
    }
}
```

```sh
Infection - PHP Mutation Testing Framework 0.16.0@b02a5a2e3eabbe8c3630e8159ec2d9b6a0966eb9
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to _HumbugBox30e9e08b3fc7\Infection\Mutator\Boolean\TrueValueConfig::__construct() must be of the type array, object
 given, called in phar://.../infection.phar/src/Mutator/MutatorFactory.php on line 24 and defined in phar://.../infection.phar/src/Mutator/Boolean/TrueValueConfig.php:13
Stack trace:
#0 phar://.../infection.phar/src/Mutator/MutatorFactory.php(24): _HumbugBox30e9e08b3fc7\Infection\Mutator\Boolean\TrueValueCon
fig->__construct(Object(stdClass))
#1 phar://.../infection.phar/src/Configuration/ConfigurationFactory.php(80): _HumbugBox30e9e08b3fc7\Infection\Mutator\MutatorF
actory->create(Array)
#2 phar://.../infection.phar/src/Configuration/ConfigurationFactory.php(46): _HumbugBox30e9e08b3fc7\Infection\Configuration\Co
nfigurationFactory->re in phar://.../infection.phar/src/Mutator/Boolean/TrueValueConfig.php on line 13
```

**Comment by maks-rafalko** [comment]
Fixed and released https://github.com/infection/infection/releases/tag/0.16.1
