### ISSUE TITLE
Notice: Trying to get property 'nodeValue' of non-object

### ISSUE THREAD

**Issue by realodix** [infection/infection#1337]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.17.6
| Test Framework version | PHPUnit 9.2.6
| PHP version | 7.4.8
| Platform    | Windows
| Github Repo | https://github.com/realodix/php-utility/tree/infection

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         bootstrap="vendor/autoload.php"
         colors="true">
    <testsuites>
        <testsuite name="Relodix Test Suite">
            <directory suffix="Test.php">./tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist>
            <directory suffix=".php">./src</directory>
        </whitelist>
    </filter>
</phpunit>

 ```
</details>

<details>
 <summary>Output with issue</summary>

 ```
     ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Infection - PHP Mutation Testing Framework version 0.17.6@941d40af2de0890dc1dcf679850124d12c9556c3


Notice: Trying to get property 'nodeValue' of non-object in C:\Users\K\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\PhpUnit\Config\XmlConfigurationManipulator.php on line 140

Fatal error: 
Uncaught TypeError: 
Argument 1 passed to Infection\TestFramework\PhpUnit\Config\XmlConfigurationManipulator::buildSchemaPath() must be of the type string, null given, called in C:\Users\K\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\PhpUnit\Config\XmlConfigurationManipulator.php on line 140 and defined in C:\Users\K\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\PhpUnit\Config\XmlConfigurationManipulator.php:181

Stack trace:
#0 C:\Users\K\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\PhpUnit\Config\XmlConfigurationManipulator.php(140): 
Infection\TestFramework\PhpUnit\Config\XmlConfigurationManipulator->buildSchemaPath(NULL)

#1 C:\Users\K\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\PhpUnit\Config\Builder\InitialConfigBuilder.php(99): Infection\TestFramework\PhpUnit\Config\XmlConfigurationManipulator->validate('C:/Users/K/AppD...', Object(Infection\TestFramework\SafeDOMXPath))

#2 C:\Users\K\AppData\Roaming\Composer in C:\Users\K\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\PhpUnit\Config\XmlConfigurationManipulator.php on line 181
 ```
</details>

**Comment by maks-rafalko** [comment]
Thank you @realodix, released https://github.com/infection/infection/releases/tag/0.17.7
