### ISSUE TITLE
Call to undefined function get_debug_type() when configuration is invalid

### ISSUE THREAD

**Issue by sstok** [infection/infection#1384]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.18.2@05685f8e97ec2d42455fdaad6984446d5af2f67e
| Test Framework version | PHPUnit 8.5.8
| PHP version | 7.4.10
| Platform    | MacOS (Docker environment)
| Github Repo | https://github.com/park-manager/park-manager/tree/infection-broken

Running infection with a wrong (not malformed) configuration file (see the repository) crashes the application
with `Call to undefined function _HumbugBox6673b05a0af0\Symfony\Component\Console\get_debug_type()`.

As this function is introduced in PHP 8.0, this might need the PHP 8 Polyfill.

<details>
 <summary>Output with issue</summary>

 ```
$ make infection

[Uncaught Error in phar:///usr/local/bin/infection/vendor/symfony/console/Application.php on line 489]
Error: Call to undefined function _HumbugBox6673b05a0af0\Symfony\Component\Console\get_debug_type() in phar:///usr/local/bin/infection/vendor/symfony/console/Application.php:489
Stack trace:
#0 phar:///usr/local/bin/infection/vendor/symfony/console/Application.php(478): _HumbugBox6673b05a0af0\Symfony\Component\Console\Application->doRenderThrowable(Object(_HumbugBox6673b05a0af0\Infection\Configuration\Schema\InvalidSchema), Object(_HumbugBox6673b05a0af0\Symfony\Component\Console\Output\StreamOutput))
#1 phar:///usr/local/bin/infection/vendor/symfony/console/Application.php(83): _HumbugBox6673b05a0af0\Symfony\Component\Console\Application->renderThrowable(Object(_HumbugBox6673b05a0af0\Infection\Configuration\Schema\InvalidSchema), Object(_HumbugBox6673b05a0af0\Symfony\Component\Console\Output\StreamOutput))
#2 phar:///usr/local/bin/infection/vendor/symfony/console/Application.php(103): _HumbugBox6673b05a0af0\Symfony\Component\Console\Application->_HumbugBox6673b05a0af0\Symfony\Component\Console\{closure}(Object(_HumbugBox6673b05a0af0\Infection\Configuration\Schema\InvalidSchema))
#3 phar:///usr/local/bin/infection/bin/infection(71): _HumbugBox6673b05a0af0\Symfony\Component\Console\Application->run()
#4 /usr/local/bin/infection(14): require('phar:///usr/loc...')
#5 {main}
make: *** [Makefile:90: in-docker-infection] Error 255
make: *** [infection] Error 2
 ```
</details>

**Comment by sstok** [comment]
Some additional information `ArrayItemRemoval` doesn't allow `ignoreSourceCodeByRegex` which marks the configuration as invalid.

**Comment by sanmai** [comment]
Chances are this is because PHP-Scooper does not know that it should keep `get_debug_type()` global.

Related to #1354

**Comment by maks-rafalko** [comment]
Released: https://github.com/infection/infection/tree/0.19.2

**Comment by sstok** [comment]
Thanks. It's working again.

And now to kill some mutants 😁

**Comment by canvural** [comment]
I encountered this issue with one of my projects today with version`0.20.0@735506ce5fc35dd504c9ba147d5fe0554898b232`

PHP 7.4.11
Downloaded infection phar from https://github.com/infection/infection/releases/download/0.20.0/infection.phar

<details>
<summary>My configuration</summary>

```json
{
    "source": {
        "directories": [
            "app"
        ],
        "excludes": [
            "Mail",
            "Nova",
            "Providers",
            "Policies"
        ]
    },
    "logs": {
        "text": "infection.log"
    },
    "mutators": {
        "@default": true
    }
}
```

</details>

<details>
<summary>Infection verbose output</summary>

```
Box Requirements Checker
========================

> Using PHP 7.4.11
> PHP is using the following php.ini file:
  /usr/local/etc/php/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.4 || ^8.0" or greater.
  ✔ The application requires the extension "zlib".
  ✔ The application requires the extension "dom".
  ✔ The application requires the extension "json".
  ✔ The application requires the extension "libxml".
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                

[debug] Checking INFECTION_ALLOW_XDEBUG
[debug] The Xdebug extension is loaded (3.0.2)
[debug] Async signals enabled (SIGINT = SIG_IGN)
[debug] Process restarting (INFECTION_ALLOW_XDEBUG=internal|3.0.2|1|*|*)
[debug] Running '/usr/local/bin/php' './infection' '--coverage=tests/_reports' '--initial-tests-php-options=-d memory_limit=-1' '-j4' '-vvv' '--ansi'

Box Requirements Checker
========================

> Using PHP 7.4.11
> PHP is using the following php.ini file:
  /tmp/KGo3AY

> Checking Box requirements:
  ✔ The application requires the version "^7.4 || ^8.0" or greater.
  ✔ The application requires the extension "zlib".
  ✔ The application requires the extension "dom".
  ✔ The application requires the extension "json".
  ✔ The application requires the extension "libxml".
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                

[debug] Checking INFECTION_ALLOW_XDEBUG
[debug] Restarted (234 ms). The Xdebug extension is not loaded
[debug] Async signals enabled (SIGINT = SIG_DFL)

    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Infection - PHP Mutation Testing Framework version 0.20.0@735506ce5fc35dd504c9ba147d5fe0554898b232


Running initial test suite...

PHPUnit version: 9.5.0

  783 [============================]  1 min

Fatal error: Uncaught Error: Call to undefined function _HumbugBoxa55ec68a3f71\Symfony\Component\Console\get_debug_type() in phar:///var/www/html/infection/vendor/symfony/console/Application.php:489
Stack trace:
#0 phar:///var/www/html/infection/vendor/symfony/console/Application.php(478): _HumbugBoxa55ec68a3f71\Symfony\Component\Console\Application->doRenderThrowable(Object(InvalidArgumentException), Object(_HumbugBoxa55ec68a3f71\Symfony\Component\Console\Output\StreamOutput))
#1 phar:///var/www/html/infection/vendor/symfony/console/Application.php(83): _HumbugBoxa55ec68a3f71\Symfony\Component\Console\Application->renderThrowable(Object(InvalidArgumentException), Object(_HumbugBoxa55ec68a3f71\Symfony\Component\Console\Output\StreamOutput))
#2 phar:///var/www/html/infection/vendor/symfony/console/Application.php(103): _HumbugBoxa55ec68a3f71\Symfony\Component\Console\Application->_HumbugBoxa55ec68a3f71\Symfony\Component\Console\{closure}(Object(InvalidArgumentException))
#3 phar:///var/www/html/infection/bin/infection(71): in phar:///var/www/html/infection/vendor/symfony/console/Application.php on line 489
[debug] Restarted process exited 255
```
</details>

Should I create a new issue?

**Comment by maks-rafalko** [comment]
yes please

**Comment by sidz** [comment]
Could you please try latest version (0.20.2) before you raise new issue? @canvural

**Comment by canvural** [comment]
@sidz PHAR from https://github.com/infection/infection/releases/tag/0.20.2 downloads `0.20.x-dev@6035c1566af6a5a8d833a276351e5e18ed412305` version. With this error message is a little different but still the same issue. Is this a dev version? How to get 0.20.2?

```
Fatal error: Uncaught Error: Call to undefined function get_debug_type() in phar:///var/www/html/infection/vendor/symfony/console/Application.php:489
Stack trace:
#0 phar:///var/www/html/infection/vendor/symfony/console/Application.php(478): _HumbugBox42c8b1b7c746\Symfony\Component\Console\Application->doRenderThrowable(Object(InvalidArgumentException), Object(_HumbugBox42c8b1b7c746\Symfony\Component\Console\Output\StreamOutput))
#1 phar:///var/www/html/infection/vendor/symfony/console/Application.php(83): _HumbugBox42c8b1b7c746\Symfony\Component\Console\Application->renderThrowable(Object(InvalidArgumentException), Object(_HumbugBox42c8b1b7c746\Symfony\Component\Console\Output\StreamOutput))
#2 phar:///var/www/html/infection/vendor/symfony/console/Application.php(103): _HumbugBox42c8b1b7c746\Symfony\Component\Console\Application->_HumbugBox42c8b1b7c746\Symfony\Component\Console\{closure}(Object(InvalidArgumentException))
#3 phar:///var/www/html/infection/bin/infection(71): _HumbugBox42c8b1b7c746\Symfony\Component\Console in phar:///var/www/html/infection/vendor/symfony/console/Application.php on line 489
```
