### ISSUE TITLE
Infection do not working on PHP 8.1.1. 

### ISSUE THREAD

**Issue by lvsantos1** [infection/infection#1662]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.4
| Test Framework version | PHPUnit
| PHP version | 8.1.1
| Platform    | Windows

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="true" backupStaticAttributes="false" bootstrap="phpunit_bootstrap.php" colors="true">
  <coverage/>
  <testsuites>
    <testsuite name="Domain">
      <directory>Domain</directory>
    </testsuite>
  </testsuites>
</phpunit>

 ```
</details>

Infection do not working on PHP 8.1.1. 

<details>
 <summary>Output with issue</summary>

 ```
PHP Fatal error:  Uncaught ValueError: Unknown format specifier "~" in C:\Users\vinic\AppData\Roaming\Composer\vendor\webmozart\assert\src\Assert.php:836
Stack trace:
#0 C:\Users\vinic\AppData\Roaming\Composer\vendor\webmozart\assert\src\Assert.php(836): sprintf()
#1 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\VersionParser.php(57): Webmozart\Assert\Assert::notSame()
#2 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\AbstractTestFrameworkAdapter.php(190): Infection\TestFramework\VersionParser->parse()
#3 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\AbstractTestFrameworkAdapter.php(131): Infection\TestFramework\AbstractTestFrameworkAdapter->retrieveVersion()
#4 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\AbstractTestFrameworkAdapter.php(141): Infection\TestFramework\AbstractTestFrameworkAdapter->getVersion()
#5 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\AbstractTestFrameworkAdapter.php(96): Infection\TestFramework\AbstractTestFrameworkAdapter->buildInitialConfigFile()
#6 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\TestFramework\PhpUnit\Adapter\PhpUnitAdapter.php(118): Infection\TestFramework\AbstractTestFrameworkAdapter->getInitialTestRunCommandLine()
#7 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\Process\Factory\InitialTestsRunProcessFactory.php(74): Infection\TestFramework\PhpUnit\Adapter\PhpUnitAdapter->getInitialTestRunCommandLine()
#8 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\Process\Runner\InitialTestsRunner.php(71): Infection\Process\Factory\InitialTestsRunProcessFactory->createProcess()
#9 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\Engine.php(137): Infection\Process\Runner\InitialTestsRunner->run()
#10 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\Engine.php(110): Infection\Engine->runInitialTestSuite()      
#11 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\Command\RunCommand.php(369): Infection\Engine->execute()      
#12 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\src\Command\BaseCommand.php(75): Infection\Command\RunCommand->executeCommand()
#13 C:\Users\vinic\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php(291): Infection\Command\BaseCommand->execute()    
#14 C:\Users\vinic\AppData\Roaming\Composer\vendor\symfony\console\Application.php(979): Symfony\Component\Console\Command\Command->run()#15 C:\Users\vinic\AppData\Roaming\Composer\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#16 C:\Users\vinic\AppData\Roaming\Composer\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun()  
#17 C:\Users\vinic\AppData\Roaming\Composer\vendor\infection\infection\bin\infection(83): Symfony\Component\Console\Application->run()   
#18 C:\Users\vinic\AppData\Roaming\Composer\vendor\bin\infection(107): include('...')
#19 {main}
  thrown in C:\Users\vinic\AppData\Roaming\Composer\vendor\webmozart\assert\src\Assert.php on line 836
 ```
</details>

**Comment by maks-rafalko** [comment]
Well, Infection itself does work on PHP 8.1.1, just checked it:

```bash
# infection repository root

docker run --rm -v "$PWD":/opt -w /opt php:8.1.1-cli sh -c "cd tests/e2e/Example_Test && phpdbg -qrr ../../../bin/infection"
```

but it seems there is an issue with `sprintf()` and values being passed to this function. Could you please dump the values of `$matched` and `$content` variables here:

https://github.com/infection/infection/blob/4a1a2fd250bc5f11d24d59803b19b705a2f67296/src/TestFramework/VersionParser.php#L54-L58

and past as a comment please? Looks like particular strings breaks `sprintf()` function

**Comment by lvsantos1** [comment]
I can yes, @maks-rafalko.

In time:

matched = int(0)

matches = array(0) {}

matches = string(30) "@php "%~dp0phpunit.phar" %*"

Thank you very much!

**Comment by maks-rafalko** [comment]
Released https://github.com/infection/infection/releases/tag/0.26.10
