### ISSUE TITLE
Call to undefined method Composer\XdebugHandler\XdebugHandler::isXdebugActive

### ISSUE THREAD

**Issue by alfredbez** [infection/infection#1677]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.25.4+ (`infection.phar --version`)
| Test Framework version | PHPUnit 9.5.18
| PHP version | 7.4.28
| Platform    | Docker on Ubuntu
| Github Repo | -

I originally posted this already as a [comment on this PR](https://github.com/infection/infection/pull/1518#issuecomment-1074833440), but I think it's better to have that as a separate issue, so here we go:
I'm getting an error since #1518 was merged and [released (in `0.25.4`)](https://github.com/infection/infection/releases/tag/0.25.4):
```
Fatal error: Uncaught Error: Call to undefined method Composer\XdebugHandler\XdebugHandler::isXdebugActive() in phar:///usr/local/bin/infection/src/TestFramework/Coverage/CoverageChecker.php:99
```

My `Dockerfile` looks like this:
```
FROM php:7.4-alpine

RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS} \
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && apk del pcre-dev ${PHPIZE_DEPS}

RUN wget https://github.com/infection/infection/releases/download/0.25.4/infection.phar \
    && wget https://github.com/infection/infection/releases/download/0.25.4/infection.phar.asc \
    && chmod +x infection.phar \
    && mv infection.phar /usr/local/bin/infection
```

The same behavior occurs in all future releases after 0.25.4.

---
I've extracted the phar and checked how that looks inside:
```
/tmp/usr/local/bin/infection $ php -r '$v = require_once("vendor/composer/installed.php"); echo $v["versions"]["composer/xdebug-handler"]["version"] . PHP_EOL;'
2.0.0.0
/tmp/usr/local/bin/infection $ grep isXdebugActive vendor/composer/xdebug-handler/src/XdebugHandler.php
    public static function isXdebugActive()
/tmp/usr/local/bin/infection $
```
---

Am I doing something wrong?

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    bootstrap="phpunit-bootstrap.php"
    executionOrder="depends,defects"
    forceCoversAnnotation="false"
    beStrictAboutCoversAnnotation="false"
    beStrictAboutOutputDuringTests="true"
    beStrictAboutTodoAnnotatedTests="true"
    colors="true"
    verbose="true">
  <coverage processUncoveredFiles="true">
    <include>
      <directory suffix=".php">src</directory>
    </include>
    <exclude>
      <directory suffix=".php">src/Orm</directory>
      <directory suffix=".php">src/Generated</directory>
    </exclude>
  </coverage>
  <testsuites>
    <testsuite name="default">
      <directory suffix="Test.php">tests/PyzUnitTest</directory>
    </testsuite>
  </testsuites>
</phpunit>
 ```
</details>

<details>
 <summary>Output with issue</summary>

 ```
Infection - PHP Mutation Testing Framework version 0.25.4.0


Fatal error: Uncaught Error: Call to undefined method Composer\XdebugHandler\XdebugHandler::isXdebugActive() in phar:///usr/local/bin/infection/src/TestFramework/Coverage/CoverageChecker.php:99
Stack trace:
#0 phar:///usr/local/bin/infection/src/TestFramework/Coverage/CoverageChecker.php(47): _HumbugBox75a5b98e45f1\Infection\TestFramework\Coverage\CoverageChecker->hasCoverageGeneratorEnabled()
#1 phar:///usr/local/bin/infection/src/Command/RunCommand.php(140): _HumbugBox75a5b98e45f1\Infection\TestFramework\Coverage\CoverageChecker->checkCoverageRequirements()
#2 phar:///usr/local/bin/infection/src/Command/RunCommand.php(72): _HumbugBox75a5b98e45f1\Infection\Command\RunCommand->startUp(Object(_HumbugBox75a5b98e45f1\Infection\Container), Object(_HumbugBox75a5b98e45f1\Infection\Console\ConsoleOutput), Object(_HumbugBox75a5b98e45f1\Infection\Logger\ConsoleLogger), Object(_HumbugBox75a5b98e45f1\Infection\Console\IO))
#3 phar:///usr/local/bin/infection/src/Command/BaseCommand.php(28): _HumbugBox75a5b98e45f1\Infection\Command\Ru in phar:///usr/local/bin/infection/src/TestFramework/Coverage/CoverageChecker.php on line 99
 ```
</details>

<details>
 <summary>How I execute infection</summary>

 I build the docker image first in the directory where my `Dockerfile` is, like so:

 ```
docker build -t alfredbez/php-xdebug .
 ```
 After that I run infection like this:
 ```
docker run --user 1000:1000 -it --rm -v $(pwd):$(pwd) -w $(pwd)/current alfredbez/php-xdebug sh -x -c 'infection'
 ```
</details>

**Comment by maks-rafalko** [comment]
As I remember, we had different issues with generated PHAR and PHP 7.4, like this one https://github.com/infection/infection/issues/1573 (which hasn't been fixed and won't be).

1. Is it possible for you to use PHP 8.0+ in your docker image?
2. Is it possible for you to use `infection/infection` composer package instead of PHAR in your image?

**Comment by alfredbez** [comment]
Just tried to use that as a composer package, but that does not work, too:

```
Infection - PHP Mutation Testing Framework version 0.25.4.0


Fatal error: Uncaught Error: Call to undefined method Composer\XdebugHandler\XdebugHandler::isXdebugActive() in /root/.composer/vendor/infection/infection/src/TestFramework/Coverage/CoverageChecker.php:176
Stack trace:
#0 /root/.composer/vendor/infection/infection/src/TestFramework/Coverage/CoverageChecker.php(102): Infection\TestFramework\Coverage\CoverageChecker->hasCoverageGeneratorEnabled()
#1 /root/.composer/vendor/infection/infection/src/Command/RunCommand.php(520): Infection\TestFramework\Coverage\CoverageChecker->checkCoverageRequirements()
#2 /root/.composer/vendor/infection/infection/src/Command/RunCommand.php(334): Infection\Command\RunCommand->startUp(Object(Infection\Container), Object(Infection\Console\ConsoleOutput), Object(Infection\Logger\ConsoleLogger), Object(Infection\Console\IO))
#3 /root/.composer/vendor/infection/infection/src/Command/BaseCommand.php(75): Infection\Command\RunCommand->executeCommand(Object(Infection\Console\IO))
#4 /home/abez/projects/project/current/vendor/symfony/console/Comma in /root/.composer/vendor/infection/infection/src/TestFramework/Coverage/CoverageChecker.php on line 176
```

Using PHP 8.0 does also not work as expected:
```
PHP 8.0.15 (cli) (built: Jan 20 2022 21:14:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Xdebug v3.1.3, Copyright (c) 2002-2022, by Derick Rethans
```

```
Infection - PHP Mutation Testing Framework version 0.25.4.0


Fatal error: Uncaught Error: Call to undefined method Composer\XdebugHandler\XdebugHandler::isXdebugActive() in phar:///usr/local/bin/infection/src/TestFramework/Coverage/CoverageChecker.php:99
Stack trace:
#0 phar:///usr/local/bin/infection/src/TestFramework/Coverage/CoverageChecker.php(47): _HumbugBox75a5b98e45f1\Infection\TestFramework\Coverage\CoverageChecker->hasCoverageGeneratorEnabled()
#1 phar:///usr/local/bin/infection/src/Command/RunCommand.php(140): _HumbugBox75a5b98e45f1\Infection\TestFramework\Coverage\CoverageChecker->checkCoverageRequirements()
#2 phar:///usr/local/bin/infection/src/Command/RunCommand.php(72): _HumbugBox75a5b98e45f1\Infection\Command\RunCommand->startUp(Object(_HumbugBox75a5b98e45f1\Infection\Container), Object(_HumbugBox75a5b98e45f1\Infection\Console\ConsoleOutput), Object(_HumbugBox75a5b98e45f1\Infection\Logger\ConsoleLogger), Object(_HumbugBox75a5b98e45f1\Infection\Console\IO))
#3 phar:///usr/local/bin/infection/src/Command/BaseCommand.php(28): _HumbugBox75a5b98e45f1\Infection\Command\RunCommand->executeCommand(Object(_HumbugBox75a5b98e45f1\Infection\Console\IO))
#4 phar:///usr/local/bin/infection/vendor/symfony/console/Command/Command.php(153): _HumbugBox75a5b98e45f1\Infection\Command\BaseCommand->execute(Object(_HumbugBox75a5b98e45f1\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox75a5b98e45f1\Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/local/bin/infection/vendor/symfony/console/Application.php(642): _HumbugBox75a5b98e45f1\Symfony\Component\Console\Command\Command->run(Object(_HumbugBox75a5b98e45f1\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox75a5b98e45f1\Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/local/bin/infection/vendor/symfony/console/Application.php(212): _HumbugBox75a5b98e45f1\Symfony\Component\Console\Application->doRunCommand(Object(_HumbugBox75a5b98e45f1\Infection\Command\RunCommand), Object(_HumbugBox75a5b98e45f1\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox75a5b98e45f1\Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/local/bin/infection/vendor/symfony/console/Application.php(120): _HumbugBox75a5b98e45f1\Symfony\Component\Console\Application->doRun(Object(_HumbugBox75a5b98e45f1\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox75a5b98e45f1\Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/local/bin/infection/bin/infection(71): _HumbugBox75a5b98e45f1\Symfony\Component\Console\Application->run()
#9 /usr/local/bin/infection(14): require('phar:///usr/loc...')
#10 {main}
  thrown in phar:///usr/local/bin/infection/src/TestFramework/Coverage/CoverageChecker.php on line 99
```

**Comment by maks-rafalko** [comment]
@deviantintegral I've just created an empty repository with only `phpunit/phpunit` composer dependency and I can't reproduce this bug.

Could you please create a minimal reproducible repository? Thank you.

**Comment by deviantintegral** [comment]
It looks like this is caused by projects having `composer/xdebug-handler` already installed at an older version.

```
composer why composer/xdebug-handler
friendsofphp/php-cs-fixer  v2.18.2  requires  composer/xdebug-handler (^1.2)
```

I'm surprised by this, because I thought the point of the phar version was to avoid such dependency issues.

I figured this out because I've since upgraded `friendsofphp/php-cs-fixer` and infection started working again. Here's a script that shows the process, the error, and fixing it.

```bash
#!/bin/bash

git clone https://github.com/deviantintegral/har.git
cd har
git checkout c839755e # Last commit before php-cs-fixer was upgraded.
composer install
echo "================"
echo "Show that phpunit tests work with coverage..."
echo "================"
#XDEBUG_MODE=coverage vendor/bin/phpunit

echo "================"
echo "Run with infection..."
echo "================"
wget https://github.com/infection/infection/releases/download/0.26.13/infection.phar
chmod +x infection.phar

cat >infection.json <<EOD
{
    "\$schema": "https://raw.githubusercontent.com/infection/infection/0.26.13/resources/schema.json",
    "source": {
        "directories": [
            "src"
        ]
    },
    "mutators": {
        "@default": true
    }
}
EOD

./infection.phar

echo "================"
echo "Show current xdebug-handler dependency..."
echo "================"
composer why composer/xdebug-handler

echo "================"
echo "Upgrade php-cs-fixer..."
echo "================"
composer require -W --dev friendsofphp/php-cs-fixer:^3

echo "================"
echo "Rerun infection..."
echo "================"
./infection.phar -j8
```

**Comment by maks-rafalko** [comment]
Thank you for all the details @deviantintegral, fixed in master
