### ISSUE TITLE
Code Coverage does not exist.

### ISSUE THREAD

**Issue by sstok** [infection/infection#179]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.1 / master
| Test Framework version | PHPUnit 6.5.6
| PHP version | PHP 7.2.2 / phpdbg (0.5.0)
| Platform    | macOS
| Github Repo | https://github.com/park-manager/park-manager/pull/37

Trying to run Infection without any special options, but keeps telling me there is no coverage detected.
Using `phpdbg` doesn't even work at all.

<details>
 <summary>Output with issue</summary>
 
 ```
$ /usr/local/bin/php -dzend_extension=/usr/local/opt/php72-xdebug/xdebug.so vendor/bin/infection -vvv
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

PHPUnit version: 6.5.6

  218 [============================] 2 secs

Generate mutants...

Processing source code files: 283/283
Creating mutated files and processes:    0/1523
In CoverageDoesNotExistException.php line 17:

  [Infection\TestFramework\Coverage\CoverageDoesNotExistException]
  Code Coverage does not exist. File /var/folders/yc/pcs364mn759f155t5mcfptrc0000gn/T/infection/coverage-xml/index.xml is not found. Check phpunit version Infection was run with and generated config files inside /var/folders/yc/pcs364mn759f155t5mcfptrc0000gn/T/infectio
  n.


Exception trace:
 Infection\TestFramework\Coverage\CoverageDoesNotExistException::with() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/src/TestFramework/Coverage/CodeCoverageData.php:153
 Infection\TestFramework\Coverage\CodeCoverageData->getCoverage() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/src/TestFramework/Coverage/CodeCoverageData.php:88
 Infection\TestFramework\Coverage\CodeCoverageData->hasExecutedMethodOnLine() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/src/Mutant/MutantCreator.php:85
 Infection\Mutant\MutantCreator->isCoveredByTest() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/src/Mutant/MutantCreator.php:68
 Infection\Mutant\MutantCreator->create() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/src/Process/Runner/MutationTestingRunner.php:65
 Infection\Process\Runner\MutationTestingRunner->Infection\Process\Runner\{closure}() at n/a:n/a
 array_map() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/src/Process/Runner/MutationTestingRunner.php:73
 Infection\Process\Runner\MutationTestingRunner->run() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/src/Command/InfectionCommand.php:193
 Infection\Command\InfectionCommand->execute() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/symfony/console/Application.php:865
 Symfony\Component\Console\Application->doRunCommand() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/symfony/console/Application.php:241
 Symfony\Component\Console\Application->doRun() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/src/Console/Application.php:50
 Infection\Console\Application->doRun() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor-bin/infection/vendor/infection/infection/bin/infection:36
 ```
</details>

<details>
 <summary>With phpdbg</summary>

```
$ phpdbg -qrr vendor/bin/infection run
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

PHPUnit version: 6.5.6

  219 [============================] 5 secs

 [ERROR] Project tests must be in a passing state before running Infection.

         Phpunit reported an exit code of 255.

         Refer to the phpunit's output below:

         STDOUT:

         PHPUnit 6.5.6 by Sebastian Bergmann and contributors.

         ...............................................................  63 / 214 ( 29%)
         ............................................................... 126 / 214 ( 58%)
         ............................................................... 189 / 214 ( 88%)
         .........................                                       214 / 214 (100%)

         Time: 4.74 seconds, Memory: 32.00MB

         OK (214 tests, 620 assertions)

         Generating code coverage report in PHPUnit XML format ...
         [PHP Notice:  Undefined offset: 0 in
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Tokenizer.php on line
         47]
         [Uncaught TypeError in
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Token.php on line 28]
         TypeError: Argument 1 passed to TheSeer\Tokenizer\Token::__construct() must be of the type integer, null given,
         called in /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Tokenizer.php on
         line 49 and defined in
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Token.php:28
         Stack trace:
         #0 /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Tokenizer.php(49):
         TheSeer\Tokenizer\Token->__construct(NULL, 'Placeholder', '')
         #1
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Source.ph
         p(37): TheSeer\Tokenizer\Tokenizer->parse('')
         #2
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(165): SebastianBergmann\CodeCoverage\Report\Xml\Source->setSourceCode('')
         #3
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(121):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->processFile(Object(SebastianBergmann\CodeCoverage\Node\File),
         Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
         #4
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(117):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory(Object(SebastianBergmann\CodeCoverage\Node\D
         irectory), Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
         #5
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(117):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory(Object(SebastianBergmann\CodeCoverage\Node\D
         irectory), Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
         #6
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(117):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory(Object(SebastianBergmann\CodeCoverage\Node\D
         irectory), Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
         #7
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(117):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory(Object(SebastianBergmann\CodeCoverage\Node\D
         irectory), Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
         #8
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(117):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory(Object(SebastianBergmann\CodeCoverage\Node\D
         irectory), Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
         #9
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(117):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory(Object(SebastianBergmann\CodeCoverage\Node\D
         irectory), Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
         #10
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p(69):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory(Object(SebastianBergmann\CodeCoverage\Node\D
         irectory), Object(SebastianBergmann\CodeCoverage\Report\Xml\Project))
         #11
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(664):
         SebastianBergmann\CodeCoverage\Report\Xml\Facade->process(Object(SebastianBergmann\CodeCoverage\CodeCoverage),
         '/var/folders/yc...')
         #12 /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/Command.php(195):
         PHPUnit\TextUI\TestRunner->doRun(NULL, Array, true)
         #13 /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/Command.php(148):
         PHPUnit\TextUI\Command->run(Array, true)
         #14 /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/phpunit(53):
         PHPUnit\TextUI\Command::main()
         #15 {main}
```
</details>

**Comment by addiks** [comment]
See #174, Enabling Xdebug on a per-process basis (Like you do with "-dzend_extension=/usr/local/opt/php72-xdebug/xdebug.so") does not work currently with infection. You must enable Xdebug permanently in the php configuration.

**Comment by sstok** [comment]
Enabled xdeug permanently now I am getting the same error as with phpdbg.

```
Notice: Undefined offset: 0 in /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Tokenizer.php on line 47
```

<details>
```
$ /usr/local/bin/php vendor/bin/infection -vvv
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

PHPUnit version: 6.5.6

  221 [============================] 15 secs

 [ERROR] Project tests must be in a passing state before running Infection.

         Phpunit reported an exit code of 255.

         Refer to the phpunit's output below:

         STDOUT:

         PHPUnit 6.5.6 by Sebastian Bergmann and contributors.

         ...............................................................  63 / 214 ( 29%)
         ............................................................... 126 / 214 ( 58%)
         ............................................................... 189 / 214 ( 88%)
         .........................                                       214 / 214 (100%)

         Time: 13.36 seconds, Memory: 26.00MB

         OK (214 tests, 620 assertions)

         Generating code coverage report in PHPUnit XML format ...
         Notice: Undefined offset: 0 in
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Tokenizer.php on line 47

         Call Stack:
             0.0005     396848   1. {main}()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/phpunit:0
             0.0054     986904   2. PHPUnit\TextUI\Command::main()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/phpunit:53
             0.0054     987016   3. PHPUnit\TextUI\Command->run()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/Command.php:148
             0.2114    7790600   4. PHPUnit\TextUI\TestRunner->doRun()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/Command.php:195
            13.3630   22414376   5. SebastianBergmann\CodeCoverage\Report\Xml\Facade->process()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:664
            14.0604   25503648   6. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:69
            14.0664   25549240   7. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.1493   24673568   8. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.3915   24673768   9. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.3916   24673936  10. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.6416   24674136  11. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.6490   24674304  12. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.6492   24674472  13. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processFile()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:121
            14.6495   24675200  14. SebastianBergmann\CodeCoverage\Report\Xml\Source->setSourceCode()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:165
            14.6495   24675256  15. TheSeer\Tokenizer\Tokenizer->parse()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Source.ph
         p:37


         Fatal error: Uncaught TypeError: Argument 1 passed to TheSeer\Tokenizer\Token::__construct() must be of the
         type integer, null given, called in
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Tokenizer.php on line 49 and
         defined in /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Token.php on line
         28

         TypeError: Argument 1 passed to TheSeer\Tokenizer\Token::__construct() must be of the type integer, null given,
         called in /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Tokenizer.php on
         line 49 in /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Token.php on line
         28

         Call Stack:
             0.0005     396848   1. {main}()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/phpunit:0
             0.0054     986904   2. PHPUnit\TextUI\Command::main()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/phpunit:53
             0.0054     987016   3. PHPUnit\TextUI\Command->run()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/Command.php:148
             0.2114    7790600   4. PHPUnit\TextUI\TestRunner->doRun()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/Command.php:195
            13.3630   22414376   5. SebastianBergmann\CodeCoverage\Report\Xml\Facade->process()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:664
            14.0604   25503648   6. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:69
            14.0664   25549240   7. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.1493   24673568   8. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.3915   24673768   9. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.3916   24673936  10. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.6416   24674136  11. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.6490   24674304  12. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:117
            14.6492   24674472  13. SebastianBergmann\CodeCoverage\Report\Xml\Facade->processFile()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:121
            14.6495   24675200  14. SebastianBergmann\CodeCoverage\Report\Xml\Source->setSourceCode()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.ph
         p:165
            14.6495   24675256  15. TheSeer\Tokenizer\Tokenizer->parse()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/phpunit/php-code-coverage/src/Report/Xml/Source.ph
         p:37
            14.6501   24689120  16. TheSeer\Tokenizer\Token->__construct()
         /Users/sebastiaanstok/Sites/park-manager/park-manager/vendor/theseer/tokenizer/src/Tokenizer.php:49
```
</details>

**Comment by sstok** [comment]
I deleted the vendor directory, and reinstalled. lets if this works 😛

**Comment by sstok** [comment]
It almost seems not all coverage is generated 🤔 looking at the infection cache directory it only generated coverage for `Bridge` but not Bundle, Component and Module.

**Comment by addiks** [comment]
I see that you are running infection from a local installation: "php ... vendor/bin/infection". Have you tried installing it globally (A) and running it from there? I also had problems with a local installation but it worked when installed globally.

A) https://infection.github.io/guide/installation.html

**Comment by theofidry** [comment]
@addiks that's very weird, if anything it should work better from a local installation

**Comment by sstok** [comment]
Same result. Wait 😧 running PHPUnit produces this result.

I applied.

```
  <logging>
    <log type="coverage-xml" target="/var/folders/yc/pcs364mn759f155t5mcfptrc0000gn/T/infection/coverage-xml"/>
    <log type="junit" target="/var/folders/yc/pcs364mn759f155t5mcfptrc0000gn/T/infection/phpunit.junit.xml"/>
  </logging>
```

 And then I got the same error 🤔

**Comment by sstok** [comment]
I found the culprit 😅 there an empty `dummy.php` file in the Tests directory, using the .dist phpunit file this is not shown because it includes this line `<directory>src/Bridge/*/Tests</directory>` which is absent in my local file 🤦‍♂️ also there was no reason for this file to be actually empty.

PHPUnit is running now. It's working! Sorry for the noise, and thanks for helping 😉
