### ISSUE TITLE
Fatal error on code `$array->{substr($key, 0, -2)}()`

### ISSUE THREAD

**Issue by vjik** [infection/infection#1799]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.26.16 (`infection.phar --version`)
| Test Framework version | PHPUnit/PhpSpec 9.5.27
| PHP version | 8.1.13
| Platform    | Windows WSL Docker
| Github Repo | https://infection-php.dev/r/3wk4

Infection throws fatal error on code:

```php
$array->{substr($key, 0, -2)}()
```

<details>
 <summary>Output with issue</summary>

 ```
Fatal error: Uncaught Error: Object of class PhpParser\Node\Arg could not be converted to string in /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php:522
Stack trace:
#0 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pExpr_MethodCall(Object(PhpParser\Node\Expr\MethodCall))
#1 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(919): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\MethodCall))
#2 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pStmt_Return(Object(PhpParser\Node\Stmt\Return_))
#3 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(293): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Return_))
#4 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(845): PhpParser\PrettyPrinterAbstract->pStmts(Array)
#5 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pStmt_If(Object(PhpParser\Node\Stmt\If_))
#6 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(293): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\If_))
#7 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(845): PhpParser\PrettyPrinterAbstract->pStmts(Array)
#8 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pStmt_If(Object(PhpParser\Node\Stmt\If_))
#9 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(293): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\If_))
#10 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(810): PhpParser\PrettyPrinterAbstract->pStmts(Array)
#11 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pStmt_ClassMethod(Object(PhpParser\Node\Stmt\ClassMethod))
#12 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(293): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\ClassMethod))
#13 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(982): PhpParser\PrettyPrinterAbstract->pStmts(Array)
#14 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(755): PhpParser\PrettyPrinter\Standard->pClassCommon(Object(PhpParser\Node\Stmt\Class_), ' ArrayHelper')
#15 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pStmt_Class(Object(PhpParser\Node\Stmt\Class_))
#16 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(293): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Class_))
#17 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(712): PhpParser\PrettyPrinterAbstract->pStmts(Array, false)
#18 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(521): PhpParser\PrettyPrinter\Standard->pStmt_Namespace(Object(PhpParser\Node\Stmt\Namespace_))
#19 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(293): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Namespace_))
#20 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(201): PhpParser\PrettyPrinterAbstract->pStmts(Array, false)
#21 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(228): PhpParser\PrettyPrinterAbstract->prettyPrint(Array)
#22 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/src/Mutant/MutantCodeFactory.php(63): PhpParser\PrettyPrinterAbstract->prettyPrintFile(Array)
#23 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/src/Mutant/MutantFactory.php(84): Infection\Mutant\MutantCodeFactory->createCode(Object(Infection\Mutation\Mutation))
#24 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/sanmai/later/src/Deferred.php(60): Infection\Mutant\MutantFactory->createMutatedCode(Object(Infection\Mutation\Mutation))
#25 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/src/Process/Runner/MutationTestingRunner.php(115): Later\Deferred->get()
#26 [internal function]: Infection\Process\Runner\MutationTestingRunner->Infection\Process\Runner\{closure}(Object(Infection\Mutant\Mutant))
#27 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/sanmai/pipeline/src/Standard.php(340): array_map(Object(Closure), Array)
#28 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/src/Process/Runner/MutationTestingRunner.php(118): Pipeline\Standard->cast(Object(Closure))
#29 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/src/Engine.php(136): Infection\Process\Runner\MutationTestingRunner->run(Array, '')
#30 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/src/Engine.php(74): Infection\Engine->runMutationAnalysis()
#31 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/src/Command/RunCommand.php(377): Infection\Engine->execute()
#32 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/src/Command/BaseCommand.php(75): Infection\Command\RunCommand->executeCommand(Object(Infection\Console\IO))
#33 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/symfony/console/Command/Command.php(312): Infection\Command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Infection\Command\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/infection/infection/bin/infection(83): Symfony\Component\Console\Application->run()
#38 /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/bin/infection(120): include('/projects/open-...')
#39 {main}
  thrown in /projects/open-source/yiisoft/yii-dev-tool/dev/arrays/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 522
 ```

</details>

**Comment by sanmai** [comment]
Sound like nikic/php-parser issue to me. Have you tried to confirm this issue is specific to Infection?

**Comment by vjik** [comment]
I'm try this code:

```php
<?php

declare(strict_types=1);

use PhpParser\Error;
use PhpParser\NodeDumper;
use PhpParser\ParserFactory;

require dirname(__DIR__) . '/vendor/autoload.php';

$code = <<<'CODE'
<?php

function test(object $object)
{
    $key = 'run()';
    $object->{substr($key, 0, -2)}();
}
CODE;

$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
try {
    $ast = $parser->parse($code);
} catch (Error $error) {
    echo "Parse error: {$error->getMessage()}\n";
    return;
}

$dumper = new NodeDumper;
echo $dumper->dump($ast) . "\n";
```

And it's work without errors.

**Comment by sidz** [comment]
Just for reference: I'm able to reproduce it in our playground: https://infection-php.dev/r/3wk4
