### ISSUE TITLE
Uncaught TypeError: PhpParser\Lexer\Emulative::__construct(): Argument #1 ($phpVersion) must be of type ?PhpParser\PhpVersion, array given

### ISSUE THREAD

**Issue by arall** [infection/infection#1911]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.27.9
| Test Framework version | PHPUnit 10.5.9
| PHP version | 8.3.0
| Platform    | MacOS
| Github Repo | -

I was using Infection with Pest for a project and worked fine for the last months. I did updated the composer dependencies and now Infection command is failing (all tests are working fine in my application).

The command I'm executing:
```sh
XDEBUG_MODE=coverage infection --threads=4 --test-framework=pest
```

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd" bootstrap="vendor/autoload.php" colors="true">
    <testsuites>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory suffix=".php">./app</directory>
        </include>
    </source>
    <php>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
        <env name="QUEUE_CONNECTION" value="database"/>
        <env name="LOG_CHANNEL" value="null"/>
    </php>
</phpunit>

 ```
</details>

<details>
 <summary>Output with issue</summary>

 ```
PHP Fatal error:  Uncaught TypeError: PhpParser\Lexer\Emulative::__construct(): Argument #1 ($phpVersion) must be of type ?PhpParser\PhpVersion, array given, called in /Users/gerard/.composer/vendor/infection/infection/src/Container.php on line 304 and defined in /Users/gerard/Code/personal/hft/vendor/nikic/php-parser/lib/PhpParser/Lexer/Emulative.php:38
Stack trace:
#0 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(304): PhpParser\Lexer\Emulative->__construct(Array)
#1 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#2 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(845): Infection\Container->get('PhpParser\\Lexer')
#3 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(307): Infection\Container->getLexer()
#4 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#5 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(850): Infection\Container->get('PhpParser\\Parse...')
#6 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(311): Infection\Container->getParser()
#7 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#8 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(855): Infection\Container->get('Infection\\PhpPa...')
#9 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(453): Infection\Container->getFileParser()
#10 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#11 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1015): Infection\Container->get('Infection\\Mutat...')
#12 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(531): Infection\Container->getFileMutationGenerator()
#13 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#14 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1065): Infection\Container->get('Infection\\Mutat...')
#15 /Users/gerard/.composer/vendor/infection/infection/src/Command/RunCommand.php(378): Infection\Container->getMutationGenerator()
#16 /Users/gerard/.composer/vendor/infection/infection/src/Command/BaseCommand.php(75): Infection\Command\RunCommand->executeCommand(Object(Infection\Console\IO))
#17 /Users/gerard/Code/personal/hft/vendor/symfony/console/Command/Command.php(326): Infection\Command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/gerard/Code/personal/hft/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/gerard/Code/personal/hft/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Infection\Command\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/gerard/Code/personal/hft/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/gerard/.composer/vendor/infection/infection/bin/infection(83): Symfony\Component\Console\Application->run()
#22 /Users/gerard/.composer/vendor/bin/infection(119): include('/Users/gerard/....')
#23 {main}
  thrown in /Users/gerard/Code/personal/hft/vendor/nikic/php-parser/lib/PhpParser/Lexer/Emulative.php on line 38

Fatal error: Uncaught TypeError: PhpParser\Lexer\Emulative::__construct(): Argument #1 ($phpVersion) must be of type ?PhpParser\PhpVersion, array given, called in /Users/gerard/.composer/vendor/infection/infection/src/Container.php on line 304 and defined in /Users/gerard/Code/personal/hft/vendor/nikic/php-parser/lib/PhpParser/Lexer/Emulative.php:38
Stack trace:
#0 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(304): PhpParser\Lexer\Emulative->__construct(Array)
#1 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#2 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(845): Infection\Container->get('PhpParser\\Lexer')
#3 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(307): Infection\Container->getLexer()
#4 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#5 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(850): Infection\Container->get('PhpParser\\Parse...')
#6 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(311): Infection\Container->getParser()
#7 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#8 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(855): Infection\Container->get('Infection\\PhpPa...')
#9 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(453): Infection\Container->getFileParser()
#10 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#11 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1015): Infection\Container->get('Infection\\Mutat...')
#12 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(531): Infection\Container->getFileMutationGenerator()
#13 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1194): Infection\Container::Infection\{closure}(Object(Infection\Container))
#14 /Users/gerard/.composer/vendor/infection/infection/src/Container.php(1065): Infection\Container->get('Infection\\Mutat...')
#15 /Users/gerard/.composer/vendor/infection/infection/src/Command/RunCommand.php(378): Infection\Container->getMutationGenerator()
#16 /Users/gerard/.composer/vendor/infection/infection/src/Command/BaseCommand.php(75): Infection\Command\RunCommand->executeCommand(Object(Infection\Console\IO))
#17 /Users/gerard/Code/personal/hft/vendor/symfony/console/Command/Command.php(326): Infection\Command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/gerard/Code/personal/hft/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/gerard/Code/personal/hft/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Infection\Command\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/gerard/Code/personal/hft/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/gerard/.composer/vendor/infection/infection/bin/infection(83): Symfony\Component\Console\Application->run()
#22 /Users/gerard/.composer/vendor/bin/infection(119): include('/Users/gerard/....')
#23 {main}
  thrown in /Users/gerard/Code/personal/hft/vendor/nikic/php-parser/lib/PhpParser/Lexer/Emulative.php on line 38
 ```
</details>

**Comment by sidz** [comment]
I didn't deep dive into this issue yet but based on the output issue is related to PHP-Parser 4.18. 

As a workaround could you please try to downgrade PHP-Parser to [4.17.1](https://github.com/nikic/PHP-Parser/releases/tag/v4.17.1)

I'll try to create PR to update PHP-Parser to 4.18 as the minimum version today

**Comment by arall** [comment]
I confim setting the `nikic/php-parser` version to `4.17.1` worked. Thanks!

**Comment by sidz** [comment]
Hey @arall 
Seems like you some how installed PHP-Parser 5 and Infection globally.

as based on the exception error Infection passed and array to Lexer while it expects PhpVersion object. So this was added in PHP-Parser 5 https://github.com/nikic/PHP-Parser/blob/v5.0.0/lib/PhpParser/Lexer/Emulative.php#L38

while PHP-Parser 4 still accepts an array: https://github.com/nikic/PHP-Parser/blob/v4.18.0/lib/PhpParser/Lexer/Emulative.php#L44


I'd say it's even not an Infection issue.

Could you please try to update to PHP-Parser 4.18 and run Infection again. I don't think that there will be an issue.

**Comment by arall** [comment]
Using `nikic/php-parser: ^4.17.1` on my project composer.json works fine. Not sure why is needed since this project has set `^4.15.1"`, uhm.... Anyway, thanks!
