### ISSUE TITLE
SourceDirGuesser failure

### ISSUE THREAD

**Issue by 3DFace** [infection/infection#23]
Trying to run first time, some troubles with SourceDirGuesser:

```
D:\Projects\php\generic-storage>D:\Tools\php7\php.exe D:\Tools\infection.phar

Welcome to the Infection config generator

We did not find configuration file. The following questions will help us to generate it for you.


PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Infection\Config\Guesser\SourceDirGuesser::Infection\Config\Guesser\{closure}() must be of the type string, array given in phar://D:/Tools/infection.phar/src/Config/Guesser/SourceDirGuesser.php:42
Stack trace:
#0 [internal function]: Infection\Config\Guesser\SourceDirGuesser->Infection\Config\Guesser\{closure}(Array)
#1 phar://D:/Tools/infection.phar/src/Config/Guesser/SourceDirGuesser.php(45): array_map(Object(Closure), Array)
#2 phar://D:/Tools/infection.phar/src/Config/Guesser/SourceDirGuesser.php(33): Infection\Config\Guesser\SourceDirGuesser->getValues('psr-0')
#3 phar://D:/Tools/infection.phar/src/Config/ValueProvider/SourceDirsProvider.php(46): Infection\Config\Guesser\SourceDirGuesser->guess()
#4 phar://D:/Tools/infection.phar/src/Command/ConfigureCommand.php(50): Infection\Config\ValueProvider\SourceDirsProvider->get(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Array)
#5 phar://D:/Tools/infection.p in phar://D:/Tools/infection.phar/src/Config/Guesser/SourceDirGuesser.php on line 42
```

**Comment by sidz** [comment]
@3DFace could you please attach `composer.json` from the `generic-storage` folder?

**Comment by sidz** [comment]
So, seems like you have invalid configuration of the `autoload` section and it looks like this:
```
"autoload": {
        "psr-4": [{
            "VendorName\\": "src/"
        }]
    },
```
but should looks like:
```
"autoload": {
        "psr-4": {
            "VendorName\\": "src/"
        }
    },
```

p.s. If I'm wrong could you please put `autoload` part from your composer.json file?

**Comment by 3DFace** [comment]
Here is my autoload section:
```
	"autoload": {
		"psr-0": {
			"": ["src/", "tests/"]
		}
	}
```
According to [docs](https://getcomposer.org/doc/04-schema.md#psr-0) entries can be "namespace to dir" relations or "namespace to multiple dirs"

**Comment by sidz** [comment]
@3DFace I've replicated that. thx.

**Comment by borNfreee** [comment]
Fixed in https://github.com/infection/infection/commit/47dca3d7d5796912d3531b1f94cffe9fbb8ca988
